set backspace=2         " backspace in insert mode works like normal editor
set expandtab           " convert tab to spaces
syntax on               " syntax highlighting
filetype indent on      " activates indenting for files
set autoindent          " auto indenting
set number              " line numbers
colorscheme desert      " colorscheme desert
set nobackup            " get rid of anoying ~file
set noswapfile          " no swapfile
set virtualedit=all     " let the cursor go anywhere
let mapleader=","       " change leader to a comma bcause the \ is too far away
map <F1> <Esc>          " avoid accidental hits of <F1> while aiming for <Esc>
